name: travel
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  simple_animations: ^1.3.9
  auto_size_text: ^2.1.0
  font_awesome_flutter: ^8.7.0
  page_transition: ^1.1.5
  provider: ^4.0.4
  http: ^0.12.0+2
  shared_preferences: ^0.5.6+2
  awesome_dialog: ^0.1.3
  firebase_auth: ^0.15.5+2
  flutter_facebook_login: ^1.2.0
  google_sign_in: ^4.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
      - family: BioRhyme
        fonts:
          - asset: fonts/BioRhyme.ttf
